import React, { useState, useEffect } from "react";
import {
  Calendar,
  CheckCircle2,
  Circle,
  Plus,
  Trash2,
  Volume2,
  Sparkles,
  TrendingUp,
  Clock,
  Target,
  Zap,
  RefreshCw,
  Award,
  ChevronRight,
  Cloud,
} from "lucide-react";
import { DailyBriefingData, ProductivityTask } from "../types";
import { SoundFX } from "../utils/soundEffects";
import { voiceManager } from "../utils/voiceManager";
import {
  auth,
  db,
  syncTaskToFirestore,
  deleteTaskFromFirestore,
  toggleTaskInFirestore,
  handleFirestoreError,
  OperationType,
} from "../lib/firebase";
import { onAuthStateChanged, type User } from "firebase/auth";
import { collection, query, orderBy, onSnapshot } from "firebase/firestore";

interface DailyProductivityProps {
  onJarvisSpeak: (text: string) => void;
  onTriggerBrowserWorkflow: (prompt: string) => void;
}

export const DailyProductivity: React.FC<DailyProductivityProps> = ({
  onJarvisSpeak,
  onTriggerBrowserWorkflow,
}) => {
  const [briefing, setBriefing] = useState<DailyBriefingData | null>(null);
  const [isLoadingBriefing, setIsLoadingBriefing] = useState(false);
  const [newTaskInput, setNewTaskInput] = useState("");
  const [taskCategory, setTaskCategory] = useState<"work" | "research" | "automation" | "personal">("work");
  const [currentUser, setCurrentUser] = useState<User | null>(null);
  const [tasks, setTasks] = useState<ProductivityTask[]>([
    {
      id: "1",
      title: "Review autonomous web scraping logs for Quantum Computing research",
      category: "automation",
      priority: "high",
      completed: true,
      autoGenerated: true,
    },
    {
      id: "2",
      title: "Execute competitive price radar across mechanical keyboard retailers",
      category: "research",
      priority: "high",
      completed: false,
      autoGenerated: true,
    },
    {
      id: "3",
      title: "Synthesize arXiv AI multimodal paper digest for engineering standup",
      category: "work",
      priority: "medium",
      completed: false,
    },
    {
      id: "4",
      title: "Review daily morning market intelligence briefing",
      category: "personal",
      priority: "medium",
      completed: false,
    },
  ]);

  // Sync tasks with Firestore for authenticated user
  useEffect(() => {
    const unsubscribeAuth = onAuthStateChanged(auth, (user) => {
      setCurrentUser(user);
      if (user) {
        const tasksPath = `users/${user.uid}/tasks`;
        const q = query(collection(db, tasksPath), orderBy("createdAt", "desc"));
        const unsubscribeTasks = onSnapshot(
          q,
          (snapshot) => {
            if (!snapshot.empty) {
              const loadedTasks: ProductivityTask[] = snapshot.docs.map((doc) => {
                const data = doc.data();
                return {
                  id: data.id || doc.id,
                  title: data.title,
                  category: data.category,
                  priority: data.priority,
                  completed: data.completed,
                };
              });
              setTasks(loadedTasks);
            }
          },
          (error) => {
            handleFirestoreError(error, OperationType.LIST, tasksPath);
          }
        );
        return () => unsubscribeTasks();
      }
    });

    return () => unsubscribeAuth();
  }, []);

  // Load daily briefing on mount
  useEffect(() => {
    const cached = sessionStorage.getItem("jarvis_daily_briefing");
    if (cached) {
      try {
        setBriefing(JSON.parse(cached));
        return;
      } catch (e) {
        // ignore parse error
      }
    }
    fetchDailyBriefing(false);
  }, []);

  const fetchDailyBriefing = async (forceRefresh: boolean = false) => {
    setIsLoadingBriefing(true);
    SoundFX.playComputeChime();
    try {
      const res = await fetch("/api/jarvis/daily-briefing", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          userLocation: "Global Intelligence Network",
          userName: "Sir",
          forceRefresh,
        }),
      });
      const data = await res.json();
      setBriefing(data);
      sessionStorage.setItem("jarvis_daily_briefing", JSON.stringify(data));
    } catch (e) {
      console.error("Failed to load briefing:", e);
    } finally {
      setIsLoadingBriefing(false);
    }
  };

  const handleSpeakBriefing = () => {
    if (!briefing) return;
    SoundFX.playWakePing();
    onJarvisSpeak(briefing.spokenAudioScript);
  };

  const toggleTask = (id: string) => {
    SoundFX.playStepComplete();
    const task = tasks.find((t) => t.id === id);
    const nextCompleted = !task?.completed;

    setTasks((prev) =>
      prev.map((t) => (t.id === id ? { ...t, completed: nextCompleted } : t))
    );

    if (currentUser) {
      toggleTaskInFirestore(currentUser.uid, id, nextCompleted).catch(console.error);
    }
  };

  const addTask = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTaskInput.trim()) return;
    SoundFX.playTargetClick();
    const newTask: ProductivityTask = {
      id: Date.now().toString(),
      title: newTaskInput.trim(),
      category: taskCategory,
      priority: "high",
      completed: false,
    };
    setTasks([newTask, ...tasks]);
    setNewTaskInput("");

    if (currentUser) {
      syncTaskToFirestore(currentUser.uid, newTask).catch(console.error);
    }
  };

  const deleteTask = (id: string) => {
    SoundFX.playTargetClick();
    setTasks((prev) => prev.filter((t) => t.id !== id));
    if (currentUser) {
      deleteTaskFromFirestore(currentUser.uid, id).catch(console.error);
    }
  };

  return (
    <div id="daily-productivity-container" className="w-full flex flex-col gap-6">
      {/* Autonomous Morning Intelligence Banner in Sophisticated Dark */}
      <div className="bg-[#0A0A0C] border border-white/5 rounded-2xl p-6 shadow-2xl relative overflow-hidden">
        <div className="flex flex-wrap items-center justify-between gap-4 border-b border-white/5 pb-4 mb-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-sky-500/10 border border-sky-500/30 text-sky-400 flex items-center justify-center shadow-[inset_0_0_15px_rgba(14,165,233,0.1)]">
              <Zap className="w-5 h-5" />
            </div>
            <div>
              <span className="text-[10px] tracking-[0.3em] uppercase text-sky-500 font-bold font-mono block mb-0.5">
                Real-Time Synthesis
              </span>
              <h2 className="text-xl font-serif italic text-white tracking-tight flex items-center gap-2">
                Autonomous Daily Intelligence Matrix
              </h2>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              id="refresh-briefing-btn"
              onClick={() => fetchDailyBriefing(true)}
              disabled={isLoadingBriefing}
              className="p-2.5 rounded-full bg-[#050506] border border-white/10 text-slate-300 hover:text-white hover:border-white/20 transition-all disabled:opacity-50"
              title="Recalibrate Briefing"
            >
              <RefreshCw className={`w-4 h-4 ${isLoadingBriefing ? "animate-spin text-sky-400" : ""}`} />
            </button>

            <button
              id="speak-briefing-btn"
              onClick={handleSpeakBriefing}
              disabled={!briefing}
              className="flex items-center gap-2 px-5 py-2 rounded-full font-mono text-xs font-semibold bg-sky-500 hover:bg-sky-400 text-white shadow-[0_0_15px_rgba(14,165,233,0.3)] transition-all"
            >
              <Volume2 className="w-4 h-4" />
              <span>VOCAL BRIEFING</span>
            </button>
          </div>
        </div>

        {/* Briefing Content */}
        {isLoadingBriefing ? (
          <div className="py-12 flex flex-col items-center justify-center gap-2 text-slate-400 font-mono text-xs">
            <RefreshCw className="w-6 h-6 animate-spin text-sky-400" />
            <span>JARVIS synthesizing live web intelligence and daily agenda...</span>
          </div>
        ) : briefing ? (
          <div className="space-y-4">
            {/* Spoken Greeting Quote Box */}
            <div className="p-4 rounded-xl bg-[#050506] border border-white/5 font-serif italic text-sm text-white/90 leading-relaxed flex items-start gap-3 shadow-inner">
              <Sparkles className="w-4 h-4 text-sky-400 shrink-0 mt-0.5" />
              <span>"{briefing.spokenAudioScript}"</span>
            </div>

            {/* Grid of Global Intelligence & Focus Priorities */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {/* Market & Tech Intelligence */}
              <div className="p-5 rounded-xl bg-[#050506] border border-white/5 space-y-3">
                <span className="text-[11px] uppercase tracking-widest text-white/40 font-mono flex items-center gap-2">
                  <TrendingUp className="w-3.5 h-3.5 text-sky-400" />
                  Live Market & Tech Pulse
                </span>
                <div className="space-y-2">
                  {briefing.marketIntelligence.map((item, idx) => (
                    <div key={idx} className="p-3 rounded-lg bg-[#0A0A0C] border border-white/5 text-xs">
                      <div className="flex items-center justify-between text-sky-400 font-serif italic font-semibold mb-1">
                        <span>{item.headline}</span>
                        <span className="text-[10px] text-slate-500 font-mono">{item.category}</span>
                      </div>
                      <p className="text-[11px] text-slate-300 leading-tight">
                        {item.summary}
                      </p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Strategic Priority Goals */}
              <div className="p-5 rounded-xl bg-[#050506] border border-white/5 space-y-3">
                <span className="text-[11px] uppercase tracking-widest text-white/40 font-mono flex items-center gap-2">
                  <Target className="w-3.5 h-3.5 text-emerald-400" />
                  Strategic Daily Priorities
                </span>
                <div className="space-y-2">
                  {briefing.productivityFocus.map((focus, idx) => (
                    <div key={idx} className="p-3 rounded-lg bg-[#0A0A0C] border border-white/5 text-xs">
                      <div className="flex items-center justify-between text-emerald-400 font-serif italic font-semibold mb-1">
                        <span>{focus.task}</span>
                        <span className="text-[10px] px-2 py-0.5 rounded-full bg-emerald-950/60 text-emerald-300 border border-emerald-800/40 font-mono">
                          {focus.priority}
                        </span>
                      </div>
                      <p className="text-[11px] text-slate-300 leading-tight">
                        Focus: {focus.actionTip}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        ) : null}
      </div>

      {/* Task Matrix & Voice Automation Planner */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Task Management Panel (8 COLS) */}
        <div className="lg:col-span-8 bg-[#0A0A0C] border border-white/5 rounded-2xl p-6 shadow-2xl space-y-5">
          <div className="flex items-center justify-between border-b border-white/5 pb-3">
            <div className="flex items-center gap-2.5">
              <span className="text-[11px] uppercase tracking-widest text-white/40 font-mono">
                Autonomous Task Matrix
              </span>
            </div>
            <span className="text-xs font-mono text-slate-400">
              {tasks.filter((t) => t.completed).length} / {tasks.length} Completed
            </span>
          </div>

          {/* Add Task Form */}
          <form onSubmit={addTask} className="flex flex-wrap sm:flex-nowrap gap-2">
            <input
              id="add-task-input"
              type="text"
              value={newTaskInput}
              onChange={(e) => setNewTaskInput(e.target.value)}
              placeholder="Add action item or speak: 'Jarvis, schedule flight research'..."
              className="flex-1 bg-[#050506] border border-white/10 rounded-full px-4 py-2.5 text-xs text-slate-100 font-serif italic focus:outline-none focus:border-sky-500/40"
            />
            <select
              value={taskCategory}
              onChange={(e: any) => setTaskCategory(e.target.value)}
              className="bg-[#050506] border border-white/10 rounded-full px-3 py-2.5 text-xs text-slate-300 font-mono focus:outline-none"
            >
              <option value="work">Work</option>
              <option value="automation">Automation</option>
              <option value="research">Research</option>
              <option value="personal">Personal</option>
            </select>
            <button
              id="add-task-submit-btn"
              type="submit"
              className="flex items-center gap-1.5 px-5 py-2.5 rounded-full font-mono text-xs font-semibold bg-sky-500 hover:bg-sky-400 text-white transition-all shadow-md"
            >
              <Plus className="w-4 h-4" />
              <span>ADD</span>
            </button>
          </form>

          {/* Tasks List */}
          <div className="space-y-2.5 max-h-[380px] overflow-y-auto pr-1">
            {tasks.map((task) => (
              <div
                key={task.id}
                className={`p-3.5 rounded-xl border text-xs flex items-center justify-between gap-3 transition-all ${
                  task.completed
                    ? "bg-white/[0.02] border-white/5 opacity-50 line-through text-slate-500"
                    : "bg-[#050506] border-white/5 text-slate-200 hover:border-white/15"
                }`}
              >
                <div
                  className="flex items-center gap-3 cursor-pointer flex-1"
                  onClick={() => toggleTask(task.id)}
                >
                  {task.completed ? (
                    <CheckCircle2 className="w-4 h-4 text-sky-400 shrink-0" />
                  ) : (
                    <Circle className="w-4 h-4 text-slate-600 hover:text-sky-400 shrink-0" />
                  )}
                  <span className="font-serif italic text-sm">{task.title}</span>
                </div>

                <div className="flex items-center gap-2">
                  <span className="text-[10px] px-2.5 py-0.5 rounded-full uppercase font-mono bg-white/5 text-slate-400 border border-white/5">
                    {task.category}
                  </span>
                  <button
                    onClick={() => deleteTask(task.id)}
                    className="p-1 rounded-full text-slate-600 hover:text-rose-400 transition-colors"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Autonomous Recurring Macros & Automation Hub (4 COLS) */}
        <div className="lg:col-span-4 bg-[#0A0A0C] border border-white/5 rounded-2xl p-6 shadow-2xl space-y-4">
          <div className="border-b border-white/5 pb-3">
            <span className="text-[11px] uppercase tracking-widest text-white/40 font-mono block mb-1">
              Autonomous Macros
            </span>
            <h3 className="text-lg font-serif italic text-white">One-Click Workflows</h3>
          </div>
          <p className="text-xs text-slate-400">
            Trigger full-stack autonomous web routines with one click or by voice command.
          </p>

          <div className="space-y-3">
            {[
              {
                title: "Morning Market Radar",
                desc: "Scans S&P500, Tech indices & commodities with live grounded analysis.",
                prompt: "Navigate to market news, analyze current tech stocks and generate executive briefing.",
              },
              {
                title: "arXiv AI Research Scraper",
                desc: "Crawls recent LLM architectures and compiles key breakthroughs.",
                prompt: "Browse arXiv AI papers, extract authors, abstracts, and benchmark results.",
              },
              {
                title: "Competitor Price Watchdog",
                desc: "Emulates browser navigation to compare e-commerce pricing tables.",
                prompt: "Compare top 3 mechanical keyboards on tech reviews and extract price table.",
              },
            ].map((macro, idx) => (
              <div
                key={idx}
                className="p-4 rounded-xl bg-[#050506] border border-white/5 hover:border-sky-500/30 transition-all group flex flex-col justify-between gap-3"
              >
                <div>
                  <h4 className="text-xs font-serif italic font-semibold text-white/90 group-hover:text-sky-300">
                    {macro.title}
                  </h4>
                  <p className="text-[11px] text-slate-400 mt-1 leading-normal">
                    {macro.desc}
                  </p>
                </div>
                <button
                  id={`launch-macro-${idx}`}
                  onClick={() => onTriggerBrowserWorkflow(macro.prompt)}
                  className="flex items-center justify-between w-full px-4 py-1.5 rounded-full bg-[#0A0A0C] border border-white/10 text-sky-400 hover:text-white hover:border-sky-500/40 text-[11px] font-mono transition-all"
                >
                  <span>ENGAGE WORKFLOW</span>
                  <ChevronRight className="w-3.5 h-3.5" />
                </button>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};
