export type JarvisState = "idle" | "listening" | "thinking" | "speaking" | "browsing" | "error";

export interface GroundingSource {
  title: string;
  url: string;
}

export interface ChatMessage {
  id: string;
  sender: "user" | "jarvis" | "system";
  text: string;
  timestamp: string;
  sources?: GroundingSource[];
  isVoiceInput?: boolean;
  browserWorkflowTriggered?: boolean;
  workflowName?: string;
  realBrowserAction?: RealBrowserAction;
  youtubeMedia?: YouTubeMedia;
  visionAnalysis?: VisionAnalysisResult;
}

export interface DetectedObjectBox {
  id: string;
  label: string;
  category: "person" | "device" | "accessory" | "furniture" | "misc";
  box2d: [number, number, number, number]; // [ymin, xmin, ymax, xmax] in normalized 0-1000 coordinates
  confidence: number; // 0-100
  threatLevel: "NOMINAL" | "LOW" | "ELEVATED";
  distanceEstimate?: string;
  colorHex?: string;
}

export interface HandTrackingData {
  isDetected: boolean;
  centroid: { x: number; y: number };
  fingertip: { x: number; y: number };
  palmCenter: { x: number; y: number };
  bounds: [number, number, number, number]; // [ymin, xmin, ymax, xmax] 0-1000
  confidence: number;
  gesture: "pointing" | "open_palm" | "pinch" | "fist" | "peace" | "unknown";
  isDrawing: boolean;
  pinchDistance?: number;
  velocity?: { vx: number; vy: number };
}

export interface AirDrawStroke {
  id: string;
  points: Array<{ x: number; y: number; pressure?: number }>;
  color: string;
  width: number;
  mode?: "laser" | "glow" | "sparkle";
  timestamp: number;
}

export interface DetectionLogEntry {
  id: string;
  timestamp: string;
  type: "hand_tracking" | "air_sketch" | "object" | "face" | "scan" | "manual_lock";
  label: string;
  category?: string;
  confidence: number;
  details?: string;
  coordinates?: string;
  sketchDataUrl?: string;
}

export interface VisionAnalysisResult {
  spokenObservation: string;
  detailedAnalysis: string;
  detectedAttributes: {
    subjectDetected: boolean;
    expression: string;
    postureStatus: string;
    ambientLighting: string;
    apparentMood: string;
    clothingStyle?: string;
    surroundingEnvironment?: string;
    detectedObjects: string[];
    threatLevel: "NOMINAL" | "LOW" | "ELEVATED";
    biometricScanConfidence: number;
  };
  detectedBoxes?: DetectedObjectBox[];
  suggestedAction?: string;
  timestamp: string;
  capturedImagePreview?: string;
}

export interface BrowserStep {
  stepNumber: number;
  actionType: "NAVIGATE" | "TYPE" | "CLICK" | "SCROLL" | "EXTRACT" | "ANALYZE" | "COMPLETE";
  description: string;
  targetElement?: string;
  inputValue?: string;
  targetUrl?: string;
  expectedOutcome: string;
  dataToExtractSample?: string;
  status?: "pending" | "running" | "completed" | "failed";
}

export interface BrowserWorkflowPlan {
  workflowName: string;
  targetWebsite: string;
  estimatedTimeSeconds: number;
  objectiveSummary: string;
  steps: BrowserStep[];
  finalExtractionSchema?: {
    summaryTitle: string;
    keyFindings: string[];
    suggestedFollowUps?: string[];
  };
}

export interface WebpageData {
  url: string;
  title: string;
  contentSnippet: string;
  links: Array<{ text: string; href: string }>;
  status: number;
  isSearchGroundingSnapshot?: boolean;
}

export interface DailyBriefingData {
  greetingTitle: string;
  spokenAudioScript: string;
  marketIntelligence: Array<{
    category: string;
    headline: string;
    summary: string;
  }>;
  productivityFocus: Array<{
    priority: string;
    task: string;
    actionTip: string;
  }>;
  motivationalThought?: string;
}

export interface ResearchDossier {
  title: string;
  executiveSummary: string;
  keyStatistics: Array<{
    metric: string;
    value: string;
    significance?: string;
  }>;
  mainPillars: Array<{
    heading: string;
    details: string;
    bulletPoints?: string[];
  }>;
  opportunitiesAndRisks: {
    opportunities: string[];
    risks: string[];
  };
  strategicRecommendations: string[];
}

export interface ProductivityTask {
  id: string;
  title: string;
  category: "work" | "research" | "automation" | "personal";
  priority: "high" | "medium" | "low";
  completed: boolean;
  dueDate?: string;
  autoGenerated?: boolean;
}

export interface TelemetryData {
  cpuUsage: number;
  memoryUsage: number;
  networkLatencyMs: number;
  uptimeSeconds: number;
  activeAgentsCount: number;
  voiceRecognitionConfidence: number;
}

export interface VoiceSettings {
  pitch: number; // 0.5 to 1.6
  rate: number;  // 0.6 to 1.8
  voiceURI?: string;
  presetName?: string;
  language?: "en-US" | "hi-IN" | "auto";
}

export interface YouTubeMedia {
  videoId: string;
  title: string;
  channelTitle?: string;
  thumbnailUrl?: string;
  isPlaying: boolean;
  isMuted: boolean;
  volume: number; // 0 to 100
  currentTime?: number;
  duration?: number;
}

export type RealBrowserActionType =
  | "OPEN_TAB"
  | "SEARCH_GOOGLE"
  | "PLAY_YOUTUBE"
  | "PAUSE_YOUTUBE"
  | "RESUME_YOUTUBE"
  | "STOP_YOUTUBE"
  | "NAVIGATE_URL"
  | "INSPECT_WEBSITE"
  | "NONE";

export interface RealBrowserAction {
  action: RealBrowserActionType;
  targetUrl?: string;
  query?: string;
  videoId?: string;
  videoTitle?: string;
  confirmationSpeech?: string;
}
